### ISSUE TITLE
Installation of components

### ISSUE THREAD

**Issue by Matzeb15** [dereisele/ha-s7#1]
Hello

Can you explain how to install your component on a fresh installed homeassistant system.
I copied your component to the [custom_components]. After restart, homeassistant found the simatic component but could not find the python snap7 lib.
I installed this also manually but after a restart i get the same error.

Do you already work on your component?

Mfg

**Comment by wolpa29** [comment]
Hey, did you fix it? I have the same problem.

**Comment by dereisele** [comment]
I've got a config something like this:

```yaml
light:
  - platform: simatic
    host: 192.168.50.9
    lib: /config/libsnap7_aarch64.so
    devices:
      - name: "Lampen Buero OG 1"
        state_address:
          byte: 4
          bit: 6
```

Because the pip in homeassistant doesn't pick the correct processor arch, you have to download the `libsnap7` somewere else and place it in the `/config` dir in home assistant
[libsnap.zip](https://github.com/dereisele/ha-s7/files/14546396/libsnap.zip)
